#include <stdbool.h>
#undef XM_STRUCT_HEADER

#undef XM_STRUCT_MEMBER_INT
#undef XM_STRUCT_MEMBER_CHAR
#undef XM_STRUCT_MEMBER_CHAR_STAR
#undef XM_STRUCT_MEMBER_LONG
#undef XM_STRUCT_MEMBER_SHORT
#undef XM_STRUCT_MEMBER_BOOL
//#undef XM_STRUCT_MEMBER_CUSTOM_T

#undef XM_STRUCT_FOOTER
