//THESE ARE ALL "X-MACRO" CALLS!
//They are defined and re-defined in multiple places in the program.
//Do not put "normal" C code in this file.



XM_STRUCT_HEADER(Character_DATA)
XM_STRUCT_MEMBER_CHAR(firstname[15])
XM_STRUCT_MEMBER_CHAR(familyname[15])
XM_STRUCT_MEMBER_CHAR(title[65])
XM_STRUCT_MEMBER_INT(level)
XM_STRUCT_MEMBER_INT(ID)
XM_STRUCT_MEMBER_INT(relation)
XM_STRUCT_MEMBER_INT(hp)
XM_STRUCT_MEMBER_INT(bhp)
XM_STRUCT_MEMBER_INT(mana)
XM_STRUCT_MEMBER_INT(bmana)
XM_STRUCT_MEMBER_INT(stamina)
XM_STRUCT_MEMBER_INT(bstamina)
XM_STRUCT_MEMBER_INT(str)
XM_STRUCT_MEMBER_INT(intel)
XM_STRUCT_MEMBER_INT(wise)
XM_STRUCT_MEMBER_INT(speech)
XM_STRUCT_MEMBER_INT(race)
XM_STRUCT_MEMBER_INT(bless)
XM_STRUCT_MEMBER_INT(job)
XM_STRUCT_MEMBER_BOOL(dead)
XM_STRUCT_MEMBER_BOOL(poison)
XM_STRUCT_MEMBER_BOOL(sleep)
XM_STRUCT_MEMBER_BOOL(male)
XM_STRUCT_MEMBER_BOOL(ennemy)
XM_STRUCT_MEMBER_BOOL(follower)

XM_STRUCT_FOOTER

XM_STRUCT_HEADER(StructB_t)
//XM_STRUCT_MEMBER_CUSTOM_T(a)
XM_STRUCT_MEMBER_CHAR_STAR(b)
XM_STRUCT_FOOTER

XM_STRUCT_HEADER(StructC_t)
XM_STRUCT_MEMBER_LONG(a)
XM_STRUCT_MEMBER_SHORT(b)
XM_STRUCT_FOOTER
